# Generated by Django 5.1 on 2024-08-19 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("food", "0002_initial"),
        ("order", "0001_initial"),
        ("restaurant", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantcart",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_Carts",
                to="restaurant.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="restaurantcart",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restaurant_carts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="order.restaurantcart",
            ),
        ),
        migrations.AddField(
            model_name="restaurantcartdish",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dishes",
                to="order.restaurantcart",
            ),
        ),
        migrations.AddField(
            model_name="restaurantcartdish",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="food.dish"
            ),
        ),
        migrations.AddField(
            model_name="restaurantpromotion",
            name="promotion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_promotions",
                to="order.promotion",
            ),
        ),
        migrations.AddField(
            model_name="restaurantpromotion",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_promotions",
                to="restaurant.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="userpromotion",
            name="promotion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_promotions",
                to="order.promotion",
            ),
        ),
        migrations.AddField(
            model_name="userpromotion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_promotions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
