# Generated by Django 3.2.7 on 2024-08-04 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliverer', '0001_initial'),
        ('order', '0001_initial'),
        ('restaurant', '0001_initial'),
        ('food', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantpromotion',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_promotions', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='restaurantcartdish',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='order.restaurantcart'),
        ),
        migrations.AddField(
            model_name='restaurantcartdish',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.dish'),
        ),
        migrations.AddField(
            model_name='restaurantcart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_carts', to='order.cart'),
        ),
        migrations.AddField(
            model_name='restaurantcart',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='orderpromotion',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_promotions', to='order.order'),
        ),
        migrations.AddField(
            model_name='orderpromotion',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderpromotion_promotions', to='order.promotion'),
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.restaurantcart'),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.promotion'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='deliverer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='deliverer.deliverer'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverers', to='order.order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitypromotion',
            name='promotion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.promotion'),
        ),
    ]
