# Generated by Django 3.2.7 on 2024-07-28 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliverer', '0002_rename_driver_license_and_vehicle_deliverer_driver_license'),
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='deliverer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='deliverer.deliverer'),
        ),
    ]
