# Generated by Django 5.1 on 2024-08-09 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderpromotion",
            name="promotion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_promotions",
                to="order.promotion",
            ),
        ),
        migrations.AlterField(
            model_name="restaurantpromotion",
            name="promotion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_promotions",
                to="order.promotion",
            ),
        ),
        migrations.AlterField(
            model_name="userpromotion",
            name="promotion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_promotions",
                to="order.promotion",
            ),
        ),
    ]
