# Generated by Django 3.2.7 on 2024-07-19 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderdish_userpromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_placed_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='raw_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.cart'),
        ),
        migrations.DeleteModel(
            name='OrderDish',
        ),
    ]
