# Generated by Django 5.1 on 2024-08-19 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0004_dish_discount_price_dish_original_price"),
        ("order", "0003_remove_order_total_restaurantcartdish_discount_price"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="restaurantcartdish",
            unique_together={("cart", "dish")},
        ),
    ]
