# Generated by Django 5.1 on 2024-08-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_order_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="rating",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
