# Generated by Django 5.1 on 2024-08-20 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_alter_order_rating"),
        ("restaurant", "0002_restaurant_avg_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantcart",
            name="restaurant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_Carts",
                to="restaurant.restaurant",
            ),
        ),
    ]
