# Generated by Django 5.1 on 2024-08-20 06:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0007_alter_restaurantcart_restaurant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurantcart",
            name="is_placed_order",
        ),
    ]
