# Generated by Django 5.1 on 2024-08-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0008_remove_restaurantcart_is_placed_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantcart",
            name="is_placed_order",
            field=models.BooleanField(default=False),
        ),
    ]
