# Generated by Django 5.1 on 2024-08-20 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0009_restaurantcart_is_placed_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurantcart",
            old_name="is_placed_order",
            new_name="is_confirmed_order",
        ),
    ]
