# Generated by Django 5.1 on 2024-08-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0004_dish_discount_price_dish_original_price"),
        ("order", "0010_rename_is_placed_order_restaurantcart_is_confirmed_order"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="restaurantcartdish",
            index=models.Index(
                fields=["cart", "dish"], name="order_resta_cart_id_d97059_idx"
            ),
        ),
    ]
