# Generated by Django 5.1 on 2024-08-20 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0011_restaurantcartdish_order_resta_cart_id_d97059_idx"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="restaurantcartdish",
            unique_together=set(),
        ),
    ]
