# Generated by Django 5.1 on 2024-08-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0012_alter_restaurantcartdish_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantcartdish",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
