# Generated by Django 5.1 on 2024-08-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0013_alter_restaurantcartdish_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantcart",
            name="is_empty",
            field=models.BooleanField(default=True),
        ),
    ]
