# Generated by Django 5.1 on 2024-08-21 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0014_restaurantcart_is_empty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurantcart",
            name="raw_fee",
        ),
    ]
