# Generated by Django 5.1 on 2024-08-23 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0007_dishoptionitem"),
        ("order", "0017_restaurantcartdish_additional_option"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChosenDishOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chosen_in_dishes",
                        to="food.dishoptionitem",
                    ),
                ),
                (
                    "restaurant_cart_dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chosen_options",
                        to="order.restaurantcartdish",
                    ),
                ),
            ],
        ),
    ]
