# Generated by Django 5.1 on 2024-08-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0007_dishoptionitem"),
        ("order", "0018_chosendishoption"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurantcartdish",
            name="additional_option",
        ),
        migrations.AddField(
            model_name="restaurantcartdish",
            name="options",
            field=models.ManyToManyField(
                related_name="in_dishes",
                through="order.ChosenDishOption",
                to="food.dishoptionitem",
            ),
        ),
    ]
