# Generated by Django 5.1 on 2024-08-23 02:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0019_remove_restaurantcartdish_additional_option_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chosendishoption",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
