# Generated by Django 5.1 on 2024-08-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0020_alter_chosendishoption_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantcartdish",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
