# Generated by Django 5.1 on 2024-08-24 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0021_restaurantcartdish_note"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurantcart",
            old_name="is_confirmed_order",
            new_name="is_created_order",
        ),
    ]
