# Generated by Django 5.1 on 2024-08-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0022_rename_is_confirmed_order_restaurantcart_is_created_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantcartdish",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
