# Generated by Django 5.1 on 2024-08-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0023_alter_restaurantcartdish_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantcart",
            name="total_items",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="restaurantcart",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
