# Generated by Django 5.1 on 2024-08-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0024_restaurantcart_total_items_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
