# Generated by Django 5.1 on 2024-08-25 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0026_remove_order_delivery_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery_fee",
        ),
    ]
