# Generated by Django 5.1 on 2024-08-27 02:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0027_remove_order_delivery_fee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="delivery",
            old_name="dropoff_lat",
            new_name="dropoff_latitude",
        ),
        migrations.RenameField(
            model_name="delivery",
            old_name="dropoff_long",
            new_name="dropoff_longitude",
        ),
        migrations.RenameField(
            model_name="delivery",
            old_name="pickup_lat",
            new_name="pickup_latitude",
        ),
        migrations.RenameField(
            model_name="delivery",
            old_name="pickup_long",
            new_name="pickup_longitude",
        ),
    ]
