# Generated by Django 5.1 on 2024-09-01 07:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0030_alter_delivery_order_alter_deliveryrequest_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryrequest",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
