# Generated by Django 5.1 on 2024-09-01 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deliverer", "0005_deliverer_delivery_requests"),
        ("order", "0031_alter_deliveryrequest_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryrequest",
            name="deliverer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="deliverer.deliverer",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryrequest",
            name="delivery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="order.delivery",
            ),
        ),
    ]
