# Generated by Django 5.1 on 2024-09-01 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0032_alter_deliveryrequest_deliverer_and_more"),
        ("restaurant", "0002_restaurant_avg_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="restaurant.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
