# Generated by Django 5.1 on 2024-09-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0034_delivery_created_at_delivery_expired_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivery",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="deliveryrequest",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("DECLINED", "Declined"),
                    ("EXPIRED", "Expired"),
                    ("CANCELLED", "Cancelled"),
                    ("DONE", "Done"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
