# Generated by Django 5.1 on 2024-09-03 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0035_alter_delivery_options_alter_deliveryrequest_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery",
                to="order.order",
            ),
        ),
    ]
