# Generated by Django 5.1 on 2024-09-05 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deliverer", "0006_rename_is_busy_deliverer_is_occupied"),
        ("order", "0038_alter_deliveryrequest_deliverer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryrequest",
            name="deliverer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="deliverer.deliverer",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryrequest",
            name="delivery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="order.delivery",
            ),
        ),
    ]
