# Generated by Django 5.1 on 2024-09-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0041_ordercancellation"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordercancellation",
            name="is_accepted",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
