# Generated by Django 5.1 on 2024-09-09 02:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0043_alter_ordercancellation_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurantcart",
            name="is_created_order",
        ),
    ]
