# Generated by Django 5.1 on 2024-09-09 06:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0044_remove_restaurantcart_is_created_order"),
        ("restaurant", "0002_restaurant_avg_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ordercancellation",
            unique_together={("user", "restaurant", "order")},
        ),
    ]
