# Generated by Django 5.1 on 2024-09-09 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0045_alter_ordercancellation_unique_together"),
        ("restaurant", "0002_restaurant_avg_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ordercancellation",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="ordercancellation",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cancellations",
                to="restaurant.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="ordercancellation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cancellations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ordercancellation",
            unique_together={("user", "restaurant")},
        ),
    ]
