# Generated by Django 5.1 on 2024-09-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0046_alter_ordercancellation_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("DECLINED", "Declined"),
                    ("EXPIRED", "Expired"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETED", "Completed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
