# Generated by Django 5.1 on 2024-09-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0047_alter_deliveryrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_deliverer_reviewed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="is_food_reviewed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="is_order_reviewed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
