# Generated by Django 5.1 on 2024-09-13 08:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0048_order_is_deliverer_reviewed_order_is_food_reviewed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="is_food_reviewed",
            new_name="is_dish_reviewed",
        ),
    ]
