# Generated by Django 5.1 on 2024-09-23 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0012_dish_is_disabled"),
        ("order", "0051_order_is_restaurant_reviewed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantcartdish",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_carts_or_orders",
                to="food.dish",
            ),
        ),
    ]
