# Generated by Django 5.1 on 2024-09-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0052_alter_restaurantcartdish_dish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
