# Generated by Django 5.1 on 2024-10-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_remove_user_promotions"),
        ("order", "0053_alter_order_created_at"),
        ("restaurant", "0015_remove_restaurant_promotions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderpromotion",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderpromotion",
            name="promotion",
        ),
        migrations.RemoveField(
            model_name="restaurantpromotion",
            name="promotion",
        ),
        migrations.RemoveField(
            model_name="restaurantpromotion",
            name="restaurant",
        ),
        migrations.RemoveField(
            model_name="userpromotion",
            name="promotion",
        ),
        migrations.RemoveField(
            model_name="userpromotion",
            name="user",
        ),
        migrations.AlterField(
            model_name="promotion",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="promo_type",
            field=models.CharField(
                choices=[("SHIPPING", "Shipping"), ("ORDER", "Order")], max_length=20
            ),
        ),
        migrations.DeleteModel(
            name="ActivityPromotion",
        ),
        migrations.DeleteModel(
            name="OrderPromotion",
        ),
        migrations.DeleteModel(
            name="RestaurantPromotion",
        ),
        migrations.DeleteModel(
            name="UserPromotion",
        ),
    ]
