# Generated by Django 5.1 on 2024-10-05 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0055_rename_promotion_restaurantpromotion_and_more"),
        ("restaurant", "0015_remove_restaurant_promotions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="restaurantpromotion",
            options={"ordering": ["-start_date", "-end_date"]},
        ),
        migrations.RemoveField(
            model_name="restaurantpromotion",
            name="active",
        ),
        migrations.AddField(
            model_name="restaurantpromotion",
            name="is_disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="restaurantpromotion",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restaurant_promotions",
                to="restaurant.restaurant",
            ),
        ),
    ]
