# Generated by Django 5.1 on 2024-10-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0056_alter_restaurantpromotion_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="restaurant_promotion",
            new_name="restaurant_promotions",
        ),
        migrations.RemoveField(
            model_name="restaurantpromotion",
            name="applicable_scope",
        ),
        migrations.AddField(
            model_name="restaurantpromotion",
            name="applicable_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="restaurantpromotion",
            name="terms_and_conditions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
