# Generated by Django 5.1 on 2024-10-05 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0058_userrestaurantpromotion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userrestaurantpromotion",
            index=models.Index(
                fields=["user", "restaurant_promotion"],
                name="order_userr_user_id_8562e1_idx",
            ),
        ),
    ]
