# Generated by Django 5.1 on 2024-10-05 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0059_userrestaurantpromotion_order_userr_user_id_8562e1_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="discount",
        ),
    ]
