# Generated by Django 5.1 on 2024-10-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0062_alter_restaurantpromotion_restaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantpromotion",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
