# Generated by Django 5.1 on 2024-10-05 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0063_restaurantpromotion_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="userrestaurantpromotion",
            name="order_userr_user_id_8562e1_idx",
        ),
        migrations.RenameField(
            model_name="userrestaurantpromotion",
            old_name="restaurant_promotion",
            new_name="promotion",
        ),
        migrations.AlterUniqueTogether(
            name="userrestaurantpromotion",
            unique_together={("user", "promotion")},
        ),
        migrations.AddIndex(
            model_name="userrestaurantpromotion",
            index=models.Index(
                fields=["user", "promotion"], name="order_userr_user_id_032a4f_idx"
            ),
        ),
    ]
