# Generated by Django 5.1 on 2024-10-06 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "order",
            "0064_remove_userrestaurantpromotion_order_userr_user_id_8562e1_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderRestaurantPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_used",
                        to="order.order",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_used",
                        to="order.restaurantpromotion",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='restaurant_promotions',
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_promotions',
            field=models.ManyToManyField(
                to='order.RestaurantPromotion',
                through='order.OrderRestaurantPromotion',
                related_name='orders',
                blank=True,
            ),
        ),
        migrations.AddIndex(
            model_name="orderrestaurantpromotion",
            index=models.Index(
                fields=["order", "promotion"], name="order_order_order_i_46999e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orderrestaurantpromotion",
            unique_together={("order", "promotion")},
        ),
    ]
