# Generated by Django 5.1 on 2024-08-19 03:23

import deliverer.models.deliverer
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deliverer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, default=0, max_digits=3, null=True
                    ),
                ),
                (
                    "total_reviews",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "rating_counts",
                    models.JSONField(
                        blank=True,
                        default=deliverer.models.deliverer.default_rating_counts,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BasicInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("given_name", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("hometown", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("ward", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("citizen_identification", models.CharField(max_length=20)),
                (
                    "deliverer",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basic_info",
                        to="deliverer.deliverer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("ward", models.CharField(max_length=100)),
                ("detail_address", models.CharField(max_length=255)),
                (
                    "deliverer",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to="deliverer.deliverer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DriverLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_front", models.ImageField(upload_to="licenses/")),
                ("license_back", models.ImageField(upload_to="licenses/")),
                ("vehicle_type", models.CharField(max_length=50)),
                ("license_plate", models.CharField(max_length=20)),
                (
                    "registration_certificate",
                    models.ImageField(upload_to="registrations/"),
                ),
                (
                    "deliverer",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_license",
                        to="deliverer.deliverer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("relationship", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "deliverer",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contact",
                        to="deliverer.deliverer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("HUB", "Tài xế HUB"),
                            ("PART_TIME", "Tài xế Part-time"),
                        ],
                        max_length=50,
                    ),
                ),
                ("operational_area", models.CharField(max_length=255)),
                ("operational_time", models.CharField(max_length=255)),
                (
                    "deliverer",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_info",
                        to="deliverer.deliverer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OtherInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occupation", models.CharField(max_length=100)),
                ("details", models.TextField()),
                ("judicial_record", models.ImageField(upload_to="judicial_records/")),
                (
                    "deliverer",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_info",
                        to="deliverer.deliverer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResidencyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_same_as_ci", models.BooleanField(default=False)),
                ("city", models.CharField(blank=True, max_length=255)),
                ("district", models.CharField(blank=True, max_length=255)),
                ("ward", models.CharField(blank=True, max_length=255)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("tax_code", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "deliverer",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="residency_info",
                        to="deliverer.deliverer",
                    ),
                ),
            ],
        ),
    ]
