# Generated by Django 3.2.7 on 2024-07-28 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('detail_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('given_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('hometown', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('citizen_identification', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_front', models.ImageField(upload_to='licenses/')),
                ('license_back', models.ImageField(upload_to='licenses/')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=20)),
                ('registration_certificate', models.ImageField(upload_to='registrations/')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OperationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('operation_type', models.CharField(choices=[('HUB', 'Tài xế HUB'), ('PART_TIME', 'Tài xế Part-time')], max_length=50)),
                ('operational_area', models.CharField(max_length=255)),
                ('operational_time', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OtherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('judicial_record', models.ImageField(upload_to='judicial_records/')),
            ],
        ),
        migrations.CreateModel(
            name='ResidencyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_same_as_ci', models.BooleanField(default=False)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=255)),
                ('ward', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('tax_code', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Deliverer',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliverer', to='deliverer.address')),
                ('basic_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliverer', to='deliverer.basicinfo')),
                ('driver_license_and_vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliverer', to='deliverer.driverlicense')),
                ('emergency_contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliverer', to='deliverer.emergencycontact')),
                ('operation_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliverer', to='deliverer.operationinfo')),
                ('other_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliverer', to='deliverer.otherinfo')),
                ('residency_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliverer', to='deliverer.residencyinfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliverer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
