# Generated by Django 3.2.7 on 2024-07-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverer',
            old_name='driver_license_and_vehicle',
            new_name='driver_license',
        ),
    ]
