# Generated by Django 5.1 on 2024-08-27 10:39

import deliverer.models.deliverer
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deliverer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverer",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=deliverer.models.deliverer.deliverer_avatar_upload_path,
            ),
        ),
    ]
