# Generated by Django 5.1 on 2024-09-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deliverer", "0002_deliverer_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverer",
            name="acceptance_rate",
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AddField(
            model_name="deliverer",
            name="accepted_requests",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="deliverer",
            name="current_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="deliverer",
            name="current_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="deliverer",
            name="is_active",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="deliverer",
            name="total_requests",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
