# Generated by Django 3.2.7 on 2024-08-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverer', '0002_rename_other_info_otherinfo_deliverer'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverer',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='deliverer',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
