# Generated by Django 3.2.7 on 2024-08-03 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliverer', '0002_rename_driver_license_and_vehicle_deliverer_driver_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverer',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverer', to='deliverer.address'),
        ),
        migrations.AlterField(
            model_name='deliverer',
            name='basic_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverer', to='deliverer.basicinfo'),
        ),
        migrations.AlterField(
            model_name='deliverer',
            name='driver_license',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverer', to='deliverer.driverlicense'),
        ),
        migrations.AlterField(
            model_name='deliverer',
            name='emergency_contact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverer', to='deliverer.emergencycontact'),
        ),
        migrations.AlterField(
            model_name='deliverer',
            name='operation_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverer', to='deliverer.operationinfo'),
        ),
        migrations.AlterField(
            model_name='deliverer',
            name='other_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverer', to='deliverer.otherinfo'),
        ),
        migrations.AlterField(
            model_name='deliverer',
            name='residency_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverer', to='deliverer.residencyinfo'),
        ),
    ]
