# Generated by Django 3.2.7 on 2024-08-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverer', '0003_auto_20240805_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverer',
            name='rating_counts',
            field=models.JSONField(default={1: 0, 2: 0, 3: 0, 4: 0, 5: 0}),
        ),
    ]
