# Generated by Django 5.1 on 2024-09-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deliverer", "0003_deliverer_acceptance_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverer",
            name="is_busy",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
