# Generated by Django 5.1 on 2024-09-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deliverer", "0004_deliverer_is_busy"),
        ("order", "0031_alter_deliveryrequest_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverer",
            name="delivery_requests",
            field=models.ManyToManyField(
                related_name="delivery_requests",
                through="order.DeliveryRequest",
                to="order.delivery",
            ),
        ),
    ]
