# Generated by Django 5.1 on 2024-09-01 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("deliverer", "0005_deliverer_delivery_requests"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliverer",
            old_name="is_busy",
            new_name="is_occupied",
        ),
    ]
