# Generated by Django 5.1 on 2024-09-17 12:17

import deliverer.models.driver_license
import deliverer.models.other_info
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "deliverer",
            "0008_rename_motorcycle_registration_certificate_driverlicense_motorcycle_registration_certificate_back_an",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverlicense",
            name="deliverer",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_license",
                to="deliverer.deliverer",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="driverlicense",
            name="driver_license_back",
            field=models.ImageField(
                default="",
                upload_to=deliverer.models.driver_license.driver_license_image_upload_path,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="driverlicense",
            name="driver_license_front",
            field=models.ImageField(
                default="/",
                upload_to=deliverer.models.driver_license.driver_license_image_upload_path,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="driverlicense",
            name="license_plate",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="driverlicense",
            name="motorcycle_registration_certificate_back",
            field=models.ImageField(
                default="",
                upload_to=deliverer.models.driver_license.registration_certificate_image_upload_path,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="driverlicense",
            name="motorcycle_registration_certificate_front",
            field=models.ImageField(
                default="",
                upload_to=deliverer.models.driver_license.registration_certificate_image_upload_path,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="driverlicense",
            name="vehicle_type",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="otherinfo",
            name="judicial_record",
            field=models.ImageField(
                default="", upload_to=deliverer.models.other_info.other_info_image_upload_path
            ),
            preserve_default=False,
        ),
    ]
