# Generated by Django 5.1 on 2024-09-17 12:31

import deliverer.models.driver_license
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deliverer", "0009_alter_driverlicense_deliverer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverlicense",
            name="deliverer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_license",
                to="deliverer.deliverer",
            ),
        ),
        migrations.AlterField(
            model_name="driverlicense",
            name="driver_license_back",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=deliverer.models.driver_license.driver_license_image_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="driverlicense",
            name="driver_license_front",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=deliverer.models.driver_license.driver_license_image_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="driverlicense",
            name="license_plate",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="driverlicense",
            name="motorcycle_registration_certificate_back",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=deliverer.models.driver_license.registration_certificate_image_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="driverlicense",
            name="motorcycle_registration_certificate_front",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=deliverer.models.driver_license.registration_certificate_image_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="driverlicense",
            name="vehicle_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
