# Generated by Django 5.1 on 2024-09-17 12:31

import deliverer.models.other_info
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deliverer", "0010_alter_driverlicense_deliverer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otherinfo",
            name="judicial_record",
            field=models.ImageField(
                blank=True, null=True, upload_to=deliverer.models.other_info.other_info_image_upload_path
            ),
        ),
    ]
