# Generated by Django 5.1 on 2024-09-21 11:53

import deliverer.models.driver_license
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deliverer", "0013_rename_operational_area_operationinfo_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverlicense",
            name="driver_license_back",
            field=models.ImageField(
                max_length=400,
                upload_to=deliverer.models.driver_license.driver_license_image_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="driverlicense",
            name="driver_license_front",
            field=models.ImageField(
                max_length=400,
                upload_to=deliverer.models.driver_license.driver_license_image_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="driverlicense",
            name="motorcycle_registration_certificate_back",
            field=models.ImageField(
                max_length=400,
                upload_to=deliverer.models.driver_license.registration_certificate_image_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="driverlicense",
            name="motorcycle_registration_certificate_front",
            field=models.ImageField(
                max_length=400,
                upload_to=deliverer.models.driver_license.registration_certificate_image_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="residencyinfo",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="residencyinfo",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="residencyinfo",
            name="district",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="residencyinfo",
            name="ward",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
