# Generated by Django 3.2.7 on 2024-08-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.ManyToManyField(related_name='commented_by_users', through='social.Comment', to='social.Post'),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_comments',
            field=models.ManyToManyField(related_name='liked_by_users', through='social.CommentLike', to='social.Comment'),
        ),
    ]
