# Generated by Django 3.2.7 on 2024-07-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_comments',
            field=models.ManyToManyField(related_name='liked_by_users', through='social.CommentLike', to='social.Comment'),
        ),
    ]
