# Generated by Django 5.1 on 2024-08-19 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("deliverer", "0001_initial"),
        ("food", "0001_initial"),
        ("notification", "0001_initial"),
        ("order", "0001_initial"),
        ("restaurant", "0001_initial"),
        ("review", "0001_initial"),
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="carts",
            field=models.ManyToManyField(
                related_name="users",
                through="order.RestaurantCart",
                to="restaurant.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="comments",
            field=models.ManyToManyField(
                related_name="commented_by_users",
                through="social.Comment",
                to="social.post",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="liked_comments",
            field=models.ManyToManyField(
                related_name="liked_by_users",
                through="social.CommentLike",
                to="social.comment",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="liked_deliverer_reviews",
            field=models.ManyToManyField(
                related_name="liked_by_users",
                through="review.DelivererReviewLike",
                to="review.delivererreview",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="liked_delivery_reviews",
            field=models.ManyToManyField(
                related_name="liked_by_users",
                through="review.DeliveryReviewLike",
                to="review.deliveryreview",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="liked_dish_reviews",
            field=models.ManyToManyField(
                related_name="liked_by_users",
                through="review.DishReviewLike",
                to="review.dishreview",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="liked_dishes",
            field=models.ManyToManyField(
                related_name="liked_by_users", through="food.DishLike", to="food.dish"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="liked_posts",
            field=models.ManyToManyField(
                related_name="liked_by_users",
                through="social.PostLike",
                to="social.post",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="liked_restaurant_reviews",
            field=models.ManyToManyField(
                related_name="liked_by_users",
                through="review.RestaurantReviewLike",
                to="review.restaurantreview",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notifications",
            field=models.ManyToManyField(
                related_name="owned_by_users",
                through="notification.UserNotification",
                to="notification.notification",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="promotions",
            field=models.ManyToManyField(
                related_name="owned_by_users",
                through="order.UserPromotion",
                to="order.promotion",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="reviewed_deliverers",
            field=models.ManyToManyField(
                related_name="reviewed_by_users",
                through="review.DelivererReview",
                to="deliverer.deliverer",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="reviewed_deliveries",
            field=models.ManyToManyField(
                related_name="reviewed_by_users",
                through="review.DeliveryReview",
                to="order.delivery",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="reviewed_dishes",
            field=models.ManyToManyField(
                related_name="reviewed_by_users",
                through="review.DishReview",
                to="food.dish",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="reviewed_restaurants",
            field=models.ManyToManyField(
                related_name="reviewed_by_users",
                through="review.RestaurantReview",
                to="restaurant.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="otp",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="setting",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="securitysetting",
            name="setting",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_setting",
                to="account.setting",
            ),
        ),
    ]
