# Generated by Django 3.2.7 on 2024-07-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20240714_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='otp',
            new_name='code',
        ),
    ]
