# Generated by Django 3.2.7 on 2024-07-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_otp_otp_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='otp_expiry',
            new_name='expired_at',
        ),
    ]
