# Generated by Django 3.2.7 on 2024-07-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('deliverer', '0002_rename_driver_license_and_vehicle_deliverer_driver_license'),
        ('order', '0003_alter_delivery_deliverer'),
        ('review', '0001_initial'),
        ('food', '0002_initial'),
        ('account', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rated_deliverers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rated_deliveries',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rated_dishes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rated_restaurants',
        ),
        migrations.AddField(
            model_name='user',
            name='reviewed_deliverers',
            field=models.ManyToManyField(related_name='reviewed_by_users', through='review.DelivererReview', to='deliverer.Deliverer'),
        ),
        migrations.AddField(
            model_name='user',
            name='reviewed_deliveries',
            field=models.ManyToManyField(related_name='reviewed_by_users', through='review.DeliveryReview', to='order.Delivery'),
        ),
        migrations.AddField(
            model_name='user',
            name='reviewed_dishes',
            field=models.ManyToManyField(related_name='reviewed_by_users', through='review.DishReview', to='food.Dish'),
        ),
        migrations.AddField(
            model_name='user',
            name='reviewed_restaurants',
            field=models.ManyToManyField(related_name='reviewed_by_users', through='review.RestaurantReview', to='restaurant.Restaurant'),
        ),
    ]
