# Generated by Django 5.1 on 2024-08-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_location_is_selected"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="name",
            field=models.TextField(
                blank=True, default="Home", max_length=200, null=True
            ),
        ),
    ]
