# Generated by Django 3.2.7 on 2024-07-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20240730_1111'),
        ('account', '0004_auto_20240730_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.ManyToManyField(related_name='commented_by_users', through='social.Comment', to='social.Post'),
        ),
    ]
