# Generated by Django 5.1 on 2024-09-15 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_alter_profile_avatar"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Location",
            new_name="UserLocation",
        ),
    ]
