# Generated by Django 3.2.7 on 2024-07-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verified',
            new_name='is_phone_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='is_registration_verified',
            field=models.BooleanField(default=False),
        ),
    ]
