# Generated by Django 3.2.7 on 2024-07-30 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='comments',
            new_name='pst_comments',
        ),
    ]
