# Generated by Django 5.1 on 2024-09-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_rename_location_userlocation"),
        ("restaurant", "0011_restaurantlike_restaurant__user_id_3406e1_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="liked_restaurants",
            field=models.ManyToManyField(
                related_name="liked_by_users",
                through="restaurant.RestaurantLike",
                to="restaurant.restaurant",
            ),
        ),
    ]
