# Generated by Django 3.2.7 on 2024-07-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20240714_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_phone_verified',
            new_name='is_otp_verified',
        ),
    ]
