# Generated by Django 3.2.7 on 2024-07-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_comments_user_pst_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pst_comments',
            new_name='comments',
        ),
    ]
