# Generated by Django 5.1 on 2024-10-05 04:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_user_liked_restaurants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="promotions",
        ),
    ]
