# Generated by Django 5.1 on 2024-10-07 07:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_user_user_restaurant_promotions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userlocation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="userlocation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
