# Generated by Django 3.2.7 on 2024-08-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='language',
            field=models.CharField(choices=[('ENGLISH', 'English'), ('VIETNAMESE', 'Vietnamese')], default='ENGLISH', max_length=30),
        ),
    ]
