# Generated by Django 3.2.7 on 2024-07-18 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        ('account', '0009_profile_securitysetting_setting_userrelation'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrelation',
            name='liked_dishes',
            field=models.ManyToManyField(blank=True, through='food.UserDish', to='food.Dish'),
        ),
        migrations.AddField(
            model_name='userrelation',
            name='messages',
            field=models.ManyToManyField(blank=True, to='notification.Message'),
        ),
        migrations.AddField(
            model_name='userrelation',
            name='notifications',
            field=models.ManyToManyField(blank=True, through='notification.UserNotification', to='notification.Notification'),
        ),
        migrations.AddField(
            model_name='userrelation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='setting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securitysetting',
            name='setting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.setting'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
