# Generated by Django 5.1 on 2024-10-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0010_alter_userlocation_options_userlocation_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlocation",
            name="address",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
