# Generated by Django 3.2.7 on 2024-07-19 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20240718_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrelation',
            name='messages',
        ),
    ]
