# Generated by Django 3.2.7 on 2024-07-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderdish_userpromotion'),
        ('food', '0001_initial'),
        ('account', '0011_remove_userrelation_messages'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrelation',
            name='promotions',
            field=models.ManyToManyField(through='order.UserPromotion', to='order.Promotion'),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='liked_dishes',
            field=models.ManyToManyField(through='food.UserDish', to='food.Dish'),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='notifications',
            field=models.ManyToManyField(through='notification.UserNotification', to='notification.Notification'),
        ),
    ]
