# Generated by Django 3.2.7 on 2024-07-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20240719_1726'),
        ('notification', '0002_auto_20240719_1726'),
        ('food', '0003_alter_userdishlike_user'),
        ('order', '0007_alter_userpromotion_user'),
        ('account', '0012_auto_20240719_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_dishes',
            field=models.ManyToManyField(through='food.UserDishLike', to='food.Dish'),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.ManyToManyField(through='notification.UserNotification', to='notification.Notification'),
        ),
        migrations.AddField(
            model_name='user',
            name='promotions',
            field=models.ManyToManyField(through='order.UserPromotion', to='order.Promotion'),
        ),
        migrations.DeleteModel(
            name='UserRelation',
        ),
    ]
