# Generated by Django 3.2.7 on 2024-07-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverer', '0001_initial'),
        ('review', '0003_auto_20240719_1726'),
        ('food', '0003_alter_userdishlike_user'),
        ('account', '0013_auto_20240719_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rated_deliverers',
            field=models.ManyToManyField(related_name='rated_by_users', through='review.DelivererReview', to='deliverer.Deliverer'),
        ),
        migrations.AddField(
            model_name='user',
            name='rated_dishes',
            field=models.ManyToManyField(through='review.DishReview', to='food.Dish'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_dishes',
            field=models.ManyToManyField(related_name='liked_dishes', through='food.UserDishLike', to='food.Dish'),
        ),
    ]
