# Generated by Django 3.2.7 on 2024-07-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20240722_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_otp_verified',
        ),
    ]
