# Generated by Django 3.2.7 on 2024-07-24 10:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_user_is_otp_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='securitysetting',
            name='setting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_setting', to='account.setting'),
        ),
    ]
