# Generated by Django 3.2.7 on 2024-07-24 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20240724_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='profile',
            new_name='user',
        ),
    ]
