# Generated by Django 5.1 on 2024-10-02 10:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="directroom",
            name="name",
        ),
    ]
