# Generated by Django 3.2.7 on 2024-08-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20240808_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directroom',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
