# Generated by Django 5.1 on 2024-10-02 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0002_remove_directroom_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="directroom",
            index=models.Index(
                fields=["user1", "user2"], name="notificatio_user1_i_104f48_idx"
            ),
        ),
    ]
