# Generated by Django 3.2.7 on 2024-08-08 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_directroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directroom',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grouproom',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grouproom',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
