# Generated by Django 5.1 on 2024-10-02 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0003_directroom_notificatio_user1_i_104f48_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="directroom",
            options={"ordering": ["latest_message__created_at"]},
        ),
        migrations.AddField(
            model_name="directroom",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
