# Generated by Django 5.1 on 2024-10-02 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0004_alter_directroom_options_directroom_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directroom",
            name="latest_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="latest_message",
                to="notification.directmessage",
            ),
        ),
    ]
