# Generated by Django 3.2.7 on 2024-08-08 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20240808_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notification.directroom'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notification.grouproom'),
        ),
    ]
