# Generated by Django 5.1 on 2024-08-09 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0006_auto_20240808_2252"),
    ]

    operations = [
        migrations.RenameField(
            model_name="directmessage",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="groupmessage",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="directmessage",
            name="image",
        ),
        migrations.RemoveField(
            model_name="directmessage",
            name="message_type",
        ),
        migrations.RemoveField(
            model_name="directmessage",
            name="video",
        ),
        migrations.RemoveField(
            model_name="groupmessage",
            name="image",
        ),
        migrations.RemoveField(
            model_name="groupmessage",
            name="message_type",
        ),
        migrations.RemoveField(
            model_name="groupmessage",
            name="video",
        ),
        migrations.CreateModel(
            name="DirectImageMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="chat_images/"),
                ),
                (
                    "direct_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_message",
                        to="notification.directmessage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DirectVideoMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="chat_videos/"),
                ),
                (
                    "direct_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_message",
                        to="notification.directmessage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupImageMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="chat_images/"),
                ),
                (
                    "group_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_message",
                        to="notification.groupmessage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupVideoMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="chat_videos/"),
                ),
                (
                    "group_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_message",
                        to="notification.groupmessage",
                    ),
                ),
            ],
        ),
    ]
