# Generated by Django 5.1 on 2024-08-09 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0008_alter_directimagemessage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directimagemessage",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="notification.directmessage",
            ),
        ),
        migrations.AlterField(
            model_name="directvideomessage",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="notification.directmessage",
            ),
        ),
        migrations.AlterField(
            model_name="groupimagemessage",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="notification.groupmessage",
            ),
        ),
        migrations.AlterField(
            model_name="groupvideomessage",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="notification.groupmessage",
            ),
        ),
    ]
