# Generated by Django 5.1 on 2024-08-09 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0009_alter_directimagemessage_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directmessage",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="notification.directroom",
            ),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="notification.grouproom",
            ),
        ),
    ]
