# Generated by Django 5.1 on 2024-08-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0012_alter_directimagemessage_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directmessage",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="content",
            field=models.TextField(default=""),
        ),
    ]
