# Generated by Django 5.1 on 2024-08-16 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0017_alter_directimagemessage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="directroom",
            name="latest_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="notification.directmessage",
            ),
        ),
        migrations.AddField(
            model_name="grouproom",
            name="latest_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="notification.groupmessage",
            ),
        ),
    ]
