# Generated by Django 5.1 on 2024-08-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0018_directroom_latest_message_grouproom_latest_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directmessage",
            name="content",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="content",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
