# Generated by Django 3.2.7 on 2024-07-30 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_initial'),
        ('restaurant', '0001_initial'),
        ('deliverer', '0002_rename_driver_license_and_vehicle_deliverer_driver_license'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivererreview',
            name='deliverer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverer_reviews', to='deliverer.deliverer'),
        ),
        migrations.AlterField(
            model_name='dishreview',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_reviews', to='food.dish'),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_reviews', to='restaurant.restaurant'),
        ),
    ]
