# Generated by Django 3.2.7 on 2024-08-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivererreview',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryreview',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dishreview',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
