# Generated by Django 5.1 on 2024-09-13 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0002_delivererreview_order_deliveryreview_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivererreview",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="deliveryreview",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="dishreview",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="restaurantreview",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterUniqueTogether(
            name="delivererreview",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="deliveryreview",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="dishreview",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="restaurantreview",
            unique_together=set(),
        ),
    ]
