# Generated by Django 3.2.7 on 2024-07-19 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0002_orderreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivererreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivererreview_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dishreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishreview_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderreview_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantreview_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
