# Generated by Django 3.2.7 on 2024-07-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20240730_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivererreview',
            old_name='comment',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='deliveryreview',
            old_name='comment',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='dishreview',
            old_name='comment',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='restaurantreview',
            old_name='comment',
            new_name='content',
        ),
    ]
