# Generated by Django 3.2.7 on 2024-07-19 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0003_auto_20240719_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantReviewLike',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_review_likes', to='review.restaurantreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantreviewlike_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'unique_together': {('user', 'review')},
            },
        ),
        migrations.CreateModel(
            name='OrderReviewLike',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_review_likes', to='review.orderreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderreviewlike_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'unique_together': {('user', 'review')},
            },
        ),
        migrations.CreateModel(
            name='DishReviewLike',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_review_likes', to='review.dishreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishreviewlike_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'unique_together': {('user', 'review')},
            },
        ),
        migrations.CreateModel(
            name='DelivererReviewLike',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverer_review_likes', to='review.delivererreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivererreviewlike_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'unique_together': {('user', 'review')},
            },
        ),
    ]
