# Generated by Django 5.1 on 2024-09-13 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deliverer", "0006_rename_is_busy_deliverer_is_occupied"),
        ("review", "0003_alter_delivererreview_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivererreview",
            name="deliverer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliverer_reviews",
                to="deliverer.deliverer",
            ),
        ),
    ]
