# Generated by Django 5.1 on 2024-09-13 15:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("deliverer", "0006_rename_is_busy_deliverer_is_occupied"),
        ("food", "0010_dishoption_is_multiple_choice"),
        ("order", "0051_order_is_restaurant_reviewed"),
        ("restaurant", "0002_restaurant_avg_price"),
        ("review", "0004_alter_delivererreview_deliverer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivererreview",
            options={},
        ),
        migrations.AlterModelOptions(
            name="deliveryreview",
            options={},
        ),
        migrations.AlterModelOptions(
            name="dishreview",
            options={},
        ),
        migrations.AlterModelOptions(
            name="restaurantreview",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="delivererreview",
            unique_together={("user", "deliverer", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="deliveryreview",
            unique_together={("user", "delivery", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="dishreview",
            unique_together={("user", "dish", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="restaurantreview",
            unique_together={("user", "restaurant", "order")},
        ),
    ]
