# Generated by Django 5.1 on 2024-09-13 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0051_order_is_restaurant_reviewed"),
        ("review", "0006_alter_delivererreview_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishreview",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dish_reviews",
                to="order.order",
            ),
        ),
    ]
