# Generated by Django 5.1 on 2024-09-14 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0051_order_is_restaurant_reviewed"),
        ("review", "0007_alter_dishreview_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivererreview",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliverer_review",
                to="order.order",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryreview",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_review",
                to="order.order",
            ),
        ),
        migrations.AlterField(
            model_name="restaurantreview",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restaurant_review",
                to="order.order",
            ),
        ),
    ]
