# Generated by Django 5.1 on 2024-09-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0008_alter_delivererreview_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivererreview",
            name="total_likes",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="deliveryreview",
            name="total_likes",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="dishreview",
            name="total_likes",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="restaurantreview",
            name="total_likes",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
