# Generated by Django 5.1 on 2024-10-02 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0010_alter_delivererreviewlike_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="delivererreviewlike",
            index=models.Index(
                fields=["user", "review"], name="review_deli_user_id_40f2b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryreviewlike",
            index=models.Index(
                fields=["user", "review"], name="review_deli_user_id_a1f47c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dishreviewlike",
            index=models.Index(
                fields=["user", "review"], name="review_dish_user_id_991232_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurantreviewlike",
            index=models.Index(
                fields=["user", "review"], name="review_rest_user_id_85271f_idx"
            ),
        ),
    ]
