# Generated by Django 5.1 on 2024-10-10 06:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0012_delivererreview_reply_deliveryreview_reply_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivererreview",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="deliveryreview",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="dishreview",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="restaurantreview",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterUniqueTogether(
            name="delivererreview",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="deliveryreview",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="dishreview",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="restaurantreview",
            unique_together=set(),
        ),
    ]
