# Generated by Django 5.1 on 2024-10-10 07:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0013_alter_delivererreview_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewReply",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reply_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.RemoveField(
            model_name="delivererreview",
            name="reply",
        ),
        migrations.RemoveField(
            model_name="deliveryreview",
            name="reply",
        ),
        migrations.RemoveField(
            model_name="dishreview",
            name="reply",
        ),
        migrations.RemoveField(
            model_name="restaurantreview",
            name="reply",
        ),
        migrations.AddField(
            model_name="delivererreview",
            name="total_replies",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="deliveryreview",
            name="total_replies",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="dishreview",
            name="total_replies",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="restaurantreview",
            name="total_replies",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name="DelivererReviewReply",
            fields=[
                (
                    "reviewreply_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="review.reviewreply",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverer_replies",
                        to="review.delivererreview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deliverer Review Reply",
                "verbose_name_plural": "Deliverer Reply Reviews",
            },
            bases=("review.reviewreply",),
        ),
        migrations.CreateModel(
            name="DeliveryReviewReply",
            fields=[
                (
                    "reviewreply_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="review.reviewreply",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_replies",
                        to="review.deliveryreview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery Review Reply",
                "verbose_name_plural": "Delivery Reply Reviews",
            },
            bases=("review.reviewreply",),
        ),
        migrations.CreateModel(
            name="DishReviewReply",
            fields=[
                (
                    "reviewreply_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="review.reviewreply",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dish_replies",
                        to="review.dishreview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dish Review Reply",
                "verbose_name_plural": "Dish Reply Reviews",
            },
            bases=("review.reviewreply",),
        ),
        migrations.CreateModel(
            name="RestaurantReviewReply",
            fields=[
                (
                    "reviewreply_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="review.reviewreply",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurant_replies",
                        to="review.restaurantreview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Restaurant Review Reply",
                "verbose_name_plural": "Restaurant Reply Reviews",
            },
            bases=("review.reviewreply",),
        ),
    ]
