# Generated by Django 5.1 on 2024-10-10 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0015_reviewimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviewimage",
            old_name="uploaded_at",
            new_name="created_at",
        ),
    ]
