# Generated by Django 5.1 on 2024-10-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0016_rename_uploaded_at_reviewimage_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewreply",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="reviewreply",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
