# Generated by Django 5.1 on 2024-10-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0017_reviewreply_title_alter_reviewreply_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewreply",
            name="content",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
