# Generated by Django 5.1 on 2024-10-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0018_alter_reviewreply_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivererreview",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="deliveryreview",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="dishreview",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="restaurantreview",
            name="content",
            field=models.TextField(default=""),
        ),
    ]
