# Generated by Django 3.2.7 on 2024-07-19 14:23

from django.db import migrations, models
import social.models.image


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentimage',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[social.models.image.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[social.models.image.validate_image_size]),
        ),
    ]
