# Generated by Django 5.1 on 2024-08-19 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("food", "0001_initial"),
        ("restaurant", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="restaurant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dishes",
                to="restaurant.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="dishadditionaloption",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_options",
                to="food.dish",
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dishes",
                to="food.dishcategory",
            ),
        ),
        migrations.AddField(
            model_name="dishlike",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="food.dish",
            ),
        ),
        migrations.AddField(
            model_name="dishlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dish_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dishsizeoption",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="size_options",
                to="food.dish",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dishlike",
            unique_together={("user", "dish")},
        ),
    ]
