# Generated by Django 3.2.7 on 2024-07-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20240719_0855'),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDish',
            new_name='UserDishLike',
        ),
    ]
