# Generated by Django 3.2.7 on 2024-07-19 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0002_rename_userdish_userdishlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdishlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
