# Generated by Django 5.1 on 2024-08-19 05:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="discount_price",
        ),
        migrations.RemoveField(
            model_name="dish",
            name="original_price",
        ),
    ]
