# Generated by Django 3.2.7 on 2024-08-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='number_of_reviews',
            new_name='total_reviews',
        ),
    ]
