# Generated by Django 5.1 on 2024-08-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0003_remove_dish_discount_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="discount_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="original_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
