# Generated by Django 3.2.7 on 2024-07-19 11:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0003_alter_userdishlike_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDishLike',
            new_name='DishLike',
        ),
    ]
