# Generated by Django 3.2.7 on 2024-08-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_rename_number_of_reviews_dish_total_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
