# Generated by Django 5.1 on 2024-08-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0004_dish_discount_price_dish_original_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="additional_option",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
