# Generated by Django 3.2.7 on 2024-07-22 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_rename_userdishlike_dishlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishSizeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='food.dish')),
            ],
        ),
    ]
