# Generated by Django 3.2.7 on 2024-08-07 01:55

from django.db import migrations, models
import food.models.dish


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_dish_rating_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='rating_counts',
            field=models.JSONField(default=food.models.dish.default_rating_counts),
        ),
    ]
