# Generated by Django 3.2.7 on 2024-07-26 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20240721_0645'),
        ('food', '0005_dishsizeoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food/category/'),
        ),
    ]
