# Generated by Django 3.2.7 on 2024-08-07 03:36

from django.db import migrations, models
import food.models.dish


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_dish_rating_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='rating_counts',
            field=models.JSONField(blank=True, default=food.models.dish.default_rating_counts, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='total_likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='total_reviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
