# Generated by Django 3.2.7 on 2024-07-26 04:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20240726_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishlike',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
