# Generated by Django 5.1 on 2024-08-23 02:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0008_remove_dishsizeoption_dish_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="additional_option",
        ),
    ]
