# Generated by Django 3.2.7 on 2024-07-26 07:13

from django.db import migrations, models
import food.models.dish


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_dishlike_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=food.models.dish.dish_image_path),
        ),
    ]
