# Generated by Django 5.1 on 2024-08-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0009_remove_dish_additional_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="dishoption",
            name="is_multiple_choice",
            field=models.BooleanField(
                default=True,
                help_text="Indicates if multiple items can be selected for this option.",
            ),
        ),
    ]
