# Generated by Django 5.1 on 2024-09-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0010_dishoption_is_multiple_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="total_orders",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
