# Generated by Django 5.1 on 2024-09-27 03:56

import django.db.models.deletion
import food.models.dish
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0012_dish_is_disabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="DishImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=food.models.dish.image_upload_path),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="food.dish",
                    ),
                ),
            ],
        ),
    ]
