# Generated by Django 5.1 on 2024-09-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0013_dishimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="is_disabled",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
