# Generated by Django 5.1 on 2024-09-27 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0014_alter_dish_is_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dish",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
