# Generated by Django 5.1 on 2024-09-28 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0015_dish_created_at_dish_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ["-created_at"]},
        ),
    ]
