# Generated by Django 5.1 on 2024-09-28 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0016_alter_dish_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={},
        ),
    ]
