# Generated by Django 5.1 on 2024-09-30 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0017_alter_dish_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dishlike",
            index=models.Index(
                fields=["user", "dish"], name="food_dishli_user_id_0ed39e_idx"
            ),
        ),
    ]
