# Generated by Django 5.1 on 2024-10-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0018_dishlike_food_dishli_user_id_0ed39e_idx"),
        ("restaurant", "0012_restaurantcategory_is_disabled"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dish",
            index=models.Index(
                fields=["category", "restaurant"], name="food_dish_categor_17c558_idx"
            ),
        ),
    ]
