# Generated by Django 5.1 on 2024-11-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0020_dish_total_revenue"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="humidity_tolerance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The acceptable tolerance for humidity (±%).",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="optimal_humidity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The ideal humidity (%) for this dish.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="optimal_temp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The ideal temperature (°C) for this dish.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="temp_tolerance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The acceptable tolerance for temperature (±°C).",
                max_digits=5,
                null=True,
            ),
        ),
    ]
