# Generated by Django 5.1 on 2024-11-17 02:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0021_dish_humidity_tolerance_dish_optimal_humidity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="humidity_tolerance",
        ),
        migrations.RemoveField(
            model_name="dish",
            name="optimal_humidity",
        ),
    ]
