# Generated by Django 3.2.7 on 2024-07-19 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('map_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DetailInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_hours', models.JSONField()),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('avatar_image', models.ImageField(upload_to='restaurant_images/')),
                ('cover_image', models.ImageField(upload_to='restaurant_images/')),
                ('facade_image', models.ImageField(upload_to='restaurant_images/')),
                ('restaurant_type', models.CharField(max_length=255)),
                ('cuisine', models.CharField(max_length=255)),
                ('specialty_dishes', models.CharField(max_length=255)),
                ('serving_times', models.CharField(max_length=255)),
                ('target_audience', models.CharField(max_length=255)),
                ('restaurant_category', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MenuDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_image', models.ImageField(upload_to='menu_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(choices=[('Cá nhân', 'Cá nhân'), ('Công ty/Chuỗi', 'Công ty/Chuỗi')], max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('other_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('id_front_image', models.ImageField(upload_to='id_images/')),
                ('id_back_image', models.ImageField(upload_to='id_images/')),
                ('business_registration_image', models.ImageField(blank=True, null=True, upload_to='business_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('basic_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_info', to='restaurant.basicinfo')),
                ('detail_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_information', to='restaurant.detailinformation')),
                ('menu_delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_delivery', to='restaurant.menudelivery')),
                ('representative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='representative', to='restaurant.representative')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=20)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('detail_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='restaurant.detailinformation')),
            ],
        ),
    ]
