# Generated by Django 5.1 on 2024-08-19 03:23

import django.db.models.deletion
import restaurant.models.restaurant
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("food", "0001_initial"),
        ("order", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DetailInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keywords", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("avatar_image", models.ImageField(upload_to="restaurant_images/")),
                ("cover_image", models.ImageField(upload_to="restaurant_images/")),
                ("facade_image", models.ImageField(upload_to="restaurant_images/")),
                ("restaurant_type", models.CharField(max_length=255)),
                ("cuisine", models.CharField(max_length=255)),
                ("specialty_dishes", models.CharField(max_length=255)),
                ("serving_times", models.CharField(max_length=255)),
                ("target_audience", models.CharField(max_length=255)),
                ("purpose", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="OperatingHour",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("day_of_week", models.CharField(max_length=20)),
                ("open_time", models.TimeField()),
                ("close_time", models.TimeField()),
                (
                    "detail_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operating_hours",
                        to="restaurant.detailinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, default=0, max_digits=3, null=True
                    ),
                ),
                (
                    "total_reviews",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "rating_counts",
                    models.JSONField(
                        blank=True,
                        default=restaurant.models.restaurant.default_rating_counts,
                        null=True,
                    ),
                ),
                (
                    "promotions",
                    models.ManyToManyField(
                        related_name="promotions",
                        through="order.RestaurantPromotion",
                        to="order.promotion",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Representative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_type",
                    models.CharField(
                        choices=[
                            ("Cá nhân", "Cá nhân"),
                            ("Công ty/Chuỗi", "Công ty/Chuỗi"),
                        ],
                        max_length=255,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "other_phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("id_front_image", models.ImageField(upload_to="id_images/")),
                ("id_back_image", models.ImageField(upload_to="id_images/")),
                (
                    "business_registration_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="business_images/"
                    ),
                ),
                (
                    "restaurant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="representative",
                        to="restaurant.restaurant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menu_image", models.ImageField(upload_to="menu_images/")),
                (
                    "restaurant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_delivery",
                        to="restaurant.restaurant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="detailinfo",
            name="restaurant",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detail_info",
                to="restaurant.restaurant",
            ),
        ),
        migrations.CreateModel(
            name="BasicInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=15)),
                ("city", models.CharField(max_length=255)),
                ("district", models.CharField(max_length=255)),
                ("street_address", models.CharField(max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "restaurant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basic_info",
                        to="restaurant.restaurant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RestaurantCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurant_categories",
                        to="food.dishcategory",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurant_categories",
                        to="restaurant.restaurant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="restaurant",
            name="categories",
            field=models.ManyToManyField(
                related_name="restaurants",
                through="restaurant.RestaurantCategory",
                to="food.dishcategory",
            ),
        ),
    ]
