# Generated by Django 5.1 on 2024-08-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="avg_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=9, null=True
            ),
        ),
    ]
