# Generated by Django 3.2.7 on 2024-07-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_userpromotion_user'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='promotions',
            field=models.ManyToManyField(related_name='promotions', to='order.RestaurantPromotion'),
        ),
    ]
