# Generated by Django 5.1 on 2024-09-17 12:52

import restaurant.models.detail_info
import restaurant.models.menu_delivery
import restaurant.models.representative_info
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_restaurant_avg_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="representative",
            name="id_back_image",
        ),
        migrations.RemoveField(
            model_name="representative",
            name="id_front_image",
        ),
        migrations.AddField(
            model_name="representative",
            name="citizen_identification_back",
            field=models.ImageField(
                default="",
                upload_to=restaurant.models.representative_info.citizen_identification_image_upload_path,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="representative",
            name="citizen_identification_front",
            field=models.ImageField(
                default="",
                upload_to=restaurant.models.representative_info.citizen_identification_image_upload_path,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="detailinfo",
            name="avatar_image",
            field=models.ImageField(
                upload_to=restaurant.models.detail_info.detail_info_image_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="detailinfo",
            name="cover_image",
            field=models.ImageField(
                upload_to=restaurant.models.detail_info.detail_info_image_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="detailinfo",
            name="facade_image",
            field=models.ImageField(
                upload_to=restaurant.models.detail_info.detail_info_image_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="menudelivery",
            name="menu_image",
            field=models.ImageField(
                upload_to=restaurant.models.menu_delivery.menu_delivery_image_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="representative",
            name="business_registration_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=restaurant.models.representative_info.business_registration_image_upload_path,
            ),
        ),
    ]
