# Generated by Django 5.1 on 2024-09-21 13:48

import django.db.models.deletion
import restaurant.models.detail_info
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0003_remove_representative_id_back_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailinfo",
            name="operating_hours",
            field=models.JSONField(
                default=restaurant.models.detail_info.default_operating_hours,
                help_text="JSON format: {'day': [{'open': 'HH:MM', 'close': 'HH:MM'}, ...] for each day}",
                validators=[restaurant.models.detail_info.validate_operating_hours],
            ),
        ),
        migrations.AlterField(
            model_name="operatinghour",
            name="detail_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operating_hours_2",
                to="restaurant.detailinfo",
            ),
        ),
    ]
