# Generated by Django 3.2.7 on 2024-07-20 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20240720_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='basic_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_info', to='restaurant.basicinfo'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='detail_information',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_information', to='restaurant.detailinformation'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu_delivery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_delivery', to='restaurant.menudelivery'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='representative',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='representative', to='restaurant.representative'),
        ),
    ]
