# Generated by Django 5.1 on 2024-09-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0004_detailinfo_operating_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="representative",
            name="citizen_identification",
            field=models.CharField(default="", max_length=20),
        ),
    ]
