# Generated by Django 3.2.7 on 2024-07-20 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20240720_2022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetailInformation',
            new_name='DetailInfo',
        ),
        migrations.RenameField(
            model_name='operatinghour',
            old_name='detail_information',
            new_name='detail_info',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='detail_information',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='detail_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail_info', to='restaurant.detailinfo'),
        ),
    ]
