# Generated by Django 3.2.7 on 2024-08-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20240805_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='map_location',
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
