# Generated by Django 5.1 on 2024-09-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0005_representative_citizen_identification"),
    ]

    operations = [
        migrations.AddField(
            model_name="representative",
            name="tax_code",
            field=models.CharField(default="", max_length=20),
        ),
    ]
