# Generated by Django 5.1 on 2024-09-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0006_representative_tax_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="representative",
            name="registration_type",
            field=models.CharField(
                choices=[
                    ("INDIVIDUAL", "Cá nhân"),
                    ("RESTAURANT_CHAIN", "Công ty/Chuỗi"),
                ],
                max_length=255,
            ),
        ),
    ]
