# Generated by Django 5.1 on 2024-09-22 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0007_alter_representative_registration_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=15)),
                ("citizen_identification", models.CharField(max_length=20)),
                ("account_name", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=30)),
                ("bank", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("branch", models.CharField(max_length=255)),
                (
                    "restaurant",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_info",
                        to="restaurant.restaurant",
                    ),
                ),
            ],
        ),
    ]
