# Generated by Django 3.2.7 on 2024-08-07 01:55

from django.db import migrations, models
import restaurant.models.restaurant


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_restaurant_rating_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rating_counts',
            field=models.JSONField(default=restaurant.models.restaurant.default_rating_counts),
        ),
    ]
