# Generated by Django 5.1 on 2024-09-22 08:04

import django.db.models.deletion
import restaurant.models.representative_info
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0008_paymentinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepresentativeInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("RESTAURANT_CHAIN", "Restaurant Chain"),
                        ],
                        max_length=255,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "other_phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("tax_code", models.CharField(default="", max_length=20)),
                ("citizen_identification", models.CharField(default="", max_length=20)),
                (
                    "citizen_identification_front",
                    models.ImageField(
                        upload_to=restaurant.models.representative_info.citizen_identification_image_upload_path
                    ),
                ),
                (
                    "citizen_identification_back",
                    models.ImageField(
                        upload_to=restaurant.models.representative_info.citizen_identification_image_upload_path
                    ),
                ),
                (
                    "business_registration_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=restaurant.models.representative_info.business_registration_image_upload_path,
                    ),
                ),
                (
                    "restaurant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="representative_info",
                        to="restaurant.restaurant",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Representative",
        ),
    ]
