# Generated by Django 3.2.7 on 2024-08-07 03:38

from django.db import migrations, models
import restaurant.models.restaurant


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_restaurant_rating_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating_counts',
            field=models.JSONField(blank=True, default=restaurant.models.restaurant.default_rating_counts, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='total_reviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
