# Generated by Django 5.1 on 2024-09-30 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0010_restaurant_total_likes_restaurantlike"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="restaurantlike",
            index=models.Index(
                fields=["user", "restaurant"], name="restaurant__user_id_3406e1_idx"
            ),
        ),
    ]
