# Generated by Django 5.1 on 2024-10-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0011_restaurantlike_restaurant__user_id_3406e1_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantcategory",
            name="is_disabled",
            field=models.BooleanField(default=False),
        ),
    ]
