# Generated by Django 5.1 on 2024-10-04 06:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0012_restaurantcategory_is_disabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantcategory",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
