# Generated by Django 5.1 on 2024-10-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0013_alter_restaurantcategory_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantcategory",
            name="is_disabled",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
