# Generated by Django 5.1 on 2024-10-05 04:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0014_alter_restaurantcategory_is_disabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="promotions",
        ),
    ]
