# Generated by Django 5.1 on 2024-10-07 06:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0015_remove_restaurant_promotions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basicinfo",
            old_name="street_address",
            new_name="address",
        ),
    ]
