# Generated by Django 5.1 on 2024-10-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0016_rename_street_address_basicinfo_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicinfo",
            name="address",
            field=models.CharField(max_length=400),
        ),
    ]
